### ISSUE TITLE
Lithuanian language support.

### ISSUE THREAD

**Issue by dziugas1959** [gl-inet/router-sdk-languages#2]
Hello,

I already translated almost all of „LuCI – Openwrt“ https://hosted.weblate.org/user/Džiugas1959/ and much more (including: „ImageGlass, Snipaste, Minecraft: Bedrock Edition, Twinkle Tray, etc.). If it is possible, I would like to be the official Lithuanian translator for „Gl-iNet“. Sadly, I don't own a „Gl-iNet“ device to double-check string locations like most of my projects. But maybe in the future; so some mistakes could happen (Has happened before). Considering that this translation project has fewer words/strings, then „Openwrt“ it shouldn't take extremely long to translate about 2200 strings/14500 words.

Hope to hear back!

**Comment by zyx0123456789zyx** [comment]
Sorry, didn't notice this entry. I have added Lithuanian. For other questions, please check your e-mail.
